FROM node:20-alpine

RUN mkdir -p /home/client
WORKDIR /home/client

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
RUN rm .env

RUN npm i -g serve

EXPOSE 3000
CMD [ "serve", "-s", "build"]
